# 语言
language: node_js
# 要测试的nodejs版本
node_js:
  - "8"
# Travis-CI Caching
cache:
  directories:
    - node_modules
#指定只有检测到master分支有变动时才执行任务
branchs:
  only:
  - master
# 安装依赖
install:
  npm install -g npm@latest
  npm --version
  npm install --registry http://registry.npmjs.org
# 运行脚本之前要全局安装依赖，不明白为什么要全局安装
before_script:
  - npm install -g less autoprefixer postcss-cli babel-cli babel-preset-env babel-preset-react
# 运行的脚本，这个脚本必须你本地能跑通，且通过
script:
  - npm run dist
